cases/urls.py
from django.urls import path
from .import views

app_name = 'cases'

urlpatterns = [
    path('createcase/', views.createcase, name='createcase'),
    path('editcases/<int:case_id>', views.edit, name='editcases'),
    path('alldateparametrs/', views.alldateparams, name='alldateparametrs'),
]

testapps/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cases/alldateparametrs', include('cases.urls')),
]

cases/models.py
from django.db import models
#from django.contrib.auth.models import User
from django.db.models import Q
import datetime


#Класс для обзорной информации предприятия/региона
class Case(models.Model):
    Case_Name = models.CharField('Название кейса', max_length=50)
    Case_Comment = models.TextField('Коментарий')
    #Is_Pattern = models.BooleanField('Шаблон', default=False)
    #Is_Pattern_For_Teacher = models.BooleanField('Шаблон для преподавателя', default=False)
    #Is_Ready = models.BooleanField('Готов к использованию', default=False)
    Case_Title = models.TextField('Наименование;ИНН')
    Case_Location = models.TextField('Год основания, месторасположения')
    Case_Type_of_activity = models.TextField('Основные виды деятельности')
    Case_Production = models.TextField('Выпускаемая продукция')

    #Is_Analitical = models.BooleanField('Задание созданное студентом', default=False)

    def __str__(self):
        return self.Case_Name

    class Meta:
        verbose_name = 'Кейс'
        verbose_name_plural = 'Кейсы'


#Класс для создания экономических параметров
class CaseParametr(models.Model):
    case = models.ForeignKey(Case, on_delete=models.CASCADE)
    Param_Name = models.CharField('Название параметра', max_length=200)
    Param_Comment = models.TextField('Коментарий')
    Name_Variable = models.CharField('Имя переменной', max_length=20, blank=True, null=True)
    Formula = models.TextField('Формула для вычисления этого параметра', blank=True, null=True)

    # Функция для вывода формулы и времени её вычислений
    def CalcInFormula(self, user):
        for date in self.dateparam_set.all():
            self.getResultInFormula(date, user)

    # Функция для преобразования текста формулы в числовое
    def replaceParam(self, dateparam, user):
        formula = self.Formula
        for param in self.case.caseparam_set.all():
            if param.Name_Variable:
                print(param.Name_Variable, dateparam.Param_Period.year)
                formula = formula.replace(param.Name_Variable, str(
                    param.dateparam_set.get(Param_Period=dateparam.Param_Period).getValue(user)))
        return formula

    # Функция для получения результата формулы
    def getResultInFormula(self, dateparam, user):
        if self.Formula:
            #Is_Prepod = user.groups.filter(name="Преподаватель").exists()
            formula = self.replaceParam(dateparam, user)
            result = None
            try:
                result = round(eval(formula), 2)
                '''if Is_Prepod:
                    dateparam.Param_Value = result
                else:'''
                dateparam.Param_UserValue = result
                dateparam.save()
            except Exception as e:
                pass
            return round(result, 2)
        return None

    def __str__(self):
        return self.Param_Name

    class Meta:
        verbose_name = 'Параметр кейса'
        verbose_name_plural = 'Параметры кейсов'


#Класс для даты создания кейса и его данных
class DateParametr(models.Model):
    case = models.ForeignKey(Case, on_delete=models.CASCADE)
    CaseParametr = models.ForeignKey(CaseParametr, on_delete=models.CASCADE)
    Param_UserValue = models.FloatField('Введенное значение пользователем', default=0)
    Param_Period = models.DateField('Период сбора данных')
    Param_Formula = models.CharField('Формула', max_length=200, default='')

    #Получить значение введённого параметра пользователем
    def getValue(self, user):
        '''if user.groups.filter(name="Преподаватель").exists():
            return self.Param_Value'''
        return self.Param_UserValue

    #Проверка правильности введённости аргументов
    def GetCheckTrueArgument(self):
        MyCase = self.Case
        #CaseOfPrepod = MyCase.jobparam_set.last().job_set.last().CaseOfPrepod
        CaseOfPrepod = MyCase.jobparam_set.last().CaseOfPrepod

        nameParam = self.CaseParam.Param_Name
        '''TrueCaseParam = CaseOfPrepod.caseparam_set.filter(NameParam=nameParam).last()
        TrueDateParam = TrueCaseParam.dateparam_set.filter(Param_Period=self.Param_Period)'''
        TrueCaseParam = CaseOfPrepod.caseparam_set.filter(NameParam=nameParam).last()
        TrueDateParam = TrueCaseParam.dateparam_set.filter(Param_Period=self.Param_Period)

        return TrueDateParam.Param_Value == self.Param_UserValue

    def __str__(self):
        return self.CaseParametr.Param_Name + " " + str(self.Param_Period.year)

    class Meta:
        verbose_name = 'Период сбора данных'
        verbose_name_plural = 'Периоды сбора данных'


# Параметр работы, содержит в себе ссылку на кейс, так же содержит в себе имя работы которое
# отображается только у студента
class JobParametr(models.Model):
    Case = models.ForeignKey(Case, on_delete=models.CASCADE)

    Param_Name = models.CharField('Наименование', max_length=50)
    Param_Help = models.CharField('Коментарий', max_length=1000)
    Param_TrueValue = models.BooleanField()
    Param_Period = models.DateField('Дата создания')

    def __str__(self):
        return self.Param_Name

    class Meta:
        verbose_name = 'Рабочий параметр'
        verbose_name_plural = 'Рабочие параметры'


# Работа - содержит в себе начала создания этой работы, содержит ссылку на пользователя который ее создал
# благодоря этому мы можем сделать права доступа на кейс, то есть другой пользователь (кроме преподавателя) не сможет посмотреть его
class Job(models.Model):
    Job_Parametr = models.ForeignKey(JobParametr, on_delete=models.CASCADE)
    #User = models.ForeignKey(User, on_delete=models.PROTECT)
    Job_Title = models.CharField('Название работы', max_length=50)
    Starting_Date = models.DateTimeField('Дата начала работы')
    Job_Status = models.BooleanField('Статус выполнения работы')
    Job_is_evaluated = models.BooleanField('Работа оценена', default=False)

    class Meta:
        verbose_name = 'Работа'
        verbose_name_plural = 'Работы'

    def __str__(self):
        return self.Job_Title


# Файлы которые заагружает преподаватель к кейсу, доументация и прочее
'''class UserFile(models.Model):
    Job = models.ForeignKey(Job, on_delete=models.CASCADE)
    #User = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь')
    File = models.FileField(upload_to='files/', max_length=100)

    class Meta:
        verbose_name = 'Файл'
        verbose_name_plural = 'Файлы'

    def __str__(self):
        return self.File.name'''


'''class GroupStud(models.Model):
    name = models.CharField(max_length=30, verbose_name='Название группы')
    users = models.ManyToManyField(User, verbose_name='Студенты')

    class Meta:
        verbose_name = 'Группа студентов'
        verbose_name_plural = 'Группы студентов'

    def __str__(self):
        return self.name'''

cases/views.py
import datetime

from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render

from cases.FormTable import CreateJobForm
from cases.models import Job, Case, CaseParametr, DateParametr, JobParametr


# Создание полноценного кейса с параметрами и разделами
@login_required
def createcase(request):
    #if request.user.groups.filter(name="Преподаватель").exists():
    if request.user.exists():
        if request.method == "POST":
            form = CreateJobForm(request.POST)
            if form.is_valid:
                case = Case(Case_Name=request.POST.get("Case_Name"), Case_Comment=request.POST.get("Case_Comment"),
                            Is_Pattern=True)
                case.save()
                Jobparametr = JobParametr.objects.create(Case=Case.objects.last(), Param_Name=case.Case_Name,
                                                   Param_Help=case.Case_Comment, Param_TrueValue=False,
                                                   Param_Period=datetime.datetime.now())
                Jobparametr.save()
                job = Job.objects.create(Job_Param=Jobparametr.objects.last(), User=request.user,
                                         Job_Title=Jobparametr.Param_Name, Starting_Date=datetime.datetime.now(),
                                         Job_Status=False)
                job.save()
                '''section = Section.objects.create(Name_Section=request.POST.get("Case_Header"), case=Case.objects.last())
                section.save()

                choice = Choice.objects.get(description=request.POST.get("selected"))'''

                '''parametr = CaseParam.objects.create(case=Case.objects.last(), section=Section.objects.last(),
                                                 choice=choice, Param_Name=request.POST.get("Case_Header"),
                                                 Param_Help='...', Param_TrueValue=False)'''
                parametr = CaseParametr.objects.create(case=Case.objects.last(),
                                                       Param_Name=request.POST.get("Case_Header"),
                                                       Param_Help='...', Param_TrueValue=False)
                parametr.save()
                i = 0
                for Param in request.POST.getlist('Param'):
                    '''Caseparam = CaseParametr.objects.create(case=Case.objects.last(), section=Section.objects.last(), 
                    choice=choice, Param_Name=Param,
                    Param_Help=request.POST.getlist('Param_Comment')[i],
                    Param_TrueValue=False)'''
                    Caseparam = CaseParametr.objects.create(case=Case.objects.last(),
                                                         Param_Name=Param,
                                                         Param_Help=request.POST.getlist('Param_Comment')[i],
                                                         Param_TrueValue=False)
                    Caseparam.save()
                    i = i + 1
                    for Period in request.POST.getlist('Period'):
                        date = datetime.date(int(Period), 1, 1)
                        Dateparam = DateParametr.objects.create(Case=Case.objects.last(),
                                                             CaseParam=CaseParametr.objects.last(), Param_UserValue=0,
                                                             Param_Value=0, Param_Period=date)
                        Dateparam.save()
                #return render(request, 'cases/cases.html', {'case': Case, 'choices': Choice.objects.all()})
                return render(request, 'cases/createcases.html', {'case': Case})
        '''else:
            sections = Choice.objects.all()
            form = CreateJobForm()
            return render(request, 'cases/createcases.html', {'form': form, 'sections': sections})'''
    else:
        return HttpResponseRedirect('/')


@login_required
def edit(request, case_id):
    #choices = Choice.objects.all()
    case = Case.objects.get(id=case_id)
    if case.jobparam_set.last().job_set.last().User == request.user:
        dateparams = DateParametr.objects.all().filter(Case_id=case.id)
        if request.method == "POST":
            for param in dateparams.all():
                param.Param_Value = request.POST.get("DateParam_" + str(param.id))
                param.save()
            for Param in CaseParametr.objects.filter(case_id=case.id).all():
                nameparam = request.POST.get("Param_" + str(Param.id))
                if nameparam:
                    Param.Param_Name = request.POST.get("Param_" + str(Param.id))
                    Param.save()
            return HttpResponseRedirect('/cases')
        #return render(request, 'cases/edit.html', {'case': case, 'choices': choices})
        return render(request, 'cases/editcases.html', {'case': case})
    else:
        return HttpResponseRedirect('/')


'''@login_required
def case_param(request):
    #if request.user.groups.filter(name="Преподаватель").exists():
    if request.user.exists():
        form = CaseParametr()
        return render(request, 'cases/createtablecases.html', {'form': form})
    return HttpResponseRedirect('/')'''

# Таблица со всеми параметрами кейса
@login_required
def allparamcases(request):
    #if request.user.groups.filter(name="Преподаватель").exists():
    if request.user.exists():
        caseParametrs = CaseParametr.objects.filter(case__Is_Pattern=True)
        for paramofcase in caseParametrs:
            if request.GET.get(str(paramofcase.id)) != None:
                paramofcase.delete()
        return render(request, 'cases/allparametrcases.html', {'caseParametrs': caseParametrs})
    return HttpResponseRedirect('/')


# Таблица со всеми параметрами параметров кейса
@login_required
def alldateparams(request):
    #if request.user.groups.filter(name="Преподаватель").exists():
    if request.user.exists():
        dateParametrs = DateParametr.objects.filter(Case__Is_Pattern=True)
        for dateparam in dateParametrs:
            if request.GET.get(str(dateparam.id)) != None:
                dateparam.delete()
                return render(request, 'cases/alldateparametrs.html', {'dateParametrs': dateParametrs})
        return render(request, 'cases/alldateparametrs.html', {'dateParametrs': dateParametrs})
    return HttpResponseRedirect('/')


'''# Редактирование параметров кейса (преподаватель), то есть преподаватель изменяет правильные значения которые будут
# использовваться в сравнении результатов студента
@login_required
def edit(request, case_id):'''

templates/cases/alldateparametrs.html
<!--{% extends 'base.html' %}-->

{%load global_context%}

{% block title %} Мои файлы {% endblock %}

{% block content %}

<h2> Формирование пакета исходных данных для анализа </h2>
<div class="container">
  <div class="row justify-content-md-cente border">
      <div class="container">
        <div class="row justify-content-md-center">
          <div class="container-fluid">
            <form method="POST">
            {%csrf_token%}
            <br>
              <div class="input-group">
                <div class="input-group-prepend">
                  <span class="input-group-text">Предприятие:</span>
                </div>
                <input class="form-control"  type="text" name="Case_Name" maxlength="100" required="" id="id_Case_Name">
              </div>
              <br>
              <div class="input-group">
                <div class="input-group-prepend">
                  <span class="input-group-text" id="">{{form.Case_Comment.label_tag}}</span>
                </div>
                <textarea class="form-control"  name="Case_Comment" maxlength="300" required="" id="id_Case_Comment"></textarea>
              </div>
            <br>

               <div class="input-group mb-3">
                <div class="input-group-prepend">
                  <label class="input-group-text" for="inputGroupSelect01">Тип раздела</label>
                </div>
                <select  class="custom-select" name="selected" id="myInput" onchange="myFunction()">
                {%for item in sections%}
                  <option name="{{item.id}}"> {{item}} </option>
                {%endfor%}
                </select>
              </div>

              <div class="input-group mb-3">
                <div class="input-group-prepend">
                  <span class="input-group-text" id="">Заголовок:</span>
                </div>
                <input class="form-control" type="text" name="Case_Header" maxlength="50" required="" id="id_Case_Header">
              </div>

              <div class ="form2">
                Параметры:
                <input name="Param" class="form-control" type="text" id="Param0" placeholder="Параметр" class="amount" required="">
                <br>
                <textarea name="Param_Comment" class="form-control" id="Case_Comment0" cols="18" rows="4"  title="Комментарий" placeholder="Комментарий" ></textarea>
                <br>
                <input  type="button" class = "add2" title="Добавить ещё один объект типа " value="Добавить"></input >
              </div>

              <div class ="form">
                <input  class="form-control" type="number" name="Period" id="Period0" placeholder="Дата" class="amount" min="1900" max="2020" required="">
                <input type="button" class = "add" title="Добавить ещё один объект типа " value="Добавить"></input >
              </div>
              <button type="submit"   > Сохранить </button>
            </form>
          </div>
        </div>
      </div>
  </div>
</div>



<script type="text/javascript"> 
  x = 0;
 var $add = document.getElementsByClassName('add')[0];
 var $form = document.getElementsByClassName('form')[0];
 var $add2 = document.getElementsByClassName('add2')[0];
 var $form2 = document.getElementsByClassName('form2')[0];
$add.addEventListener('click', function(event) {
  date = new Date();

  if(x < 6 ){
  var $input = document.createElement('input');
  $input.type = 'number';
  $input.id = 'Period'+ x +'';
  $input.name = 'Period';
  $input.required = '';
  $input.placeholder = 'Дата';
  $input.classList.add('amount');
  $input.min = 1900;
  $input.classList.add("form-control");
  $input.max = date.getFullYear();
  $form.insertBefore($input, $add);
  x++;

}
});
y =1;
$add2.addEventListener('click', function(event) {
  date = new Date();

  var $input2 = document.createElement('input');
  $input2.type = 'text';
  $input2.required = '';
  $input2.id = 'Param'+ y +'';
  $input2.name = 'Param';
  $input2.classList.add("form-control");
  $input2.placeholder = 'Параметр';
  $input2.classList.add('amount');
  $form2.insertBefore($input2, $add2);

  var $br2 = document.createElement('br');
  $form2.insertBefore($br2, $add2);

  var $input3  = document.createElement('textarea');
  $input3.cols = "18";
  $input3.rows = "4";
  $input3.title = "Комментарий";
  $input3.placeholder="Комментарий";
  $input3.name = 'Param_Comment';
  $input3.classList.add("form-control");
  $input3.id = "Param_Comment" + y;
  $form2.insertBefore($input3, $add2);

  var $br2 = document.createElement('br');
  $form2.insertBefore($br2, $add2);
  y++;
});
</script>

{% endblock %}

templates/cases/allparametrcases.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/cases/createcase.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/cases/createcases.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/cases/editcases.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>